#!/usr/bin/env sh
set -e
check()
{
    yes=`which $1 | wc -l`
    echo $yes
}
status=`check docker`
if [ "$status" = 0 ]; then
	apt-get update
	apt-get -y install apt-transport-https ca-certificates curl software-properties-common
	curl -fsSL http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo apt-key add -
	add-apt-repository "deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
	apt-get -y update
	apt-get -y install docker-ce
fi
mkdir -p /etc/docker
tee /etc/docker/daemon.json <<-'EOF'
{
  "registry-mirrors": ["https://vwypw7yj.mirror.aliyuncs.com"]
  ,"insecure-registries" : ["docker.dever.cc"]
}
EOF
service docker restart

chmod -R +x src/*.py
chmod -R +x src/shell
chmod -R 777 container/share/
basepath=$(cd `dirname $0`; pwd)
ln -sf $basepath/src/dm.py /usr/bin/dm && chmod +x /usr/bin/dm
ln -sf $basepath/src/dp.py /usr/bin/dp && chmod +x /usr/bin/dp
ln -sf $basepath/src/dpc.py /usr/bin/dpc && chmod +x /usr/bin/dpc
ln -sf $basepath/src/dever.py /usr/bin/dever && chmod +x /usr/bin/dever
ln -sf $basepath/src/dgit.py /usr/bin/dgit && chmod +x /usr/bin/dgit

docker version
echo 'install success!'