#!/usr/bin/env sh
set -e

#docker ps -a|awk '{print $1}'|xargs docker rm -f 
result=`docker ps -a|grep Exited|awk '{print $1}'`
if [ -n "$result" ];then
	docker ps -a|grep Exited|awk '{print $1}'|xargs docker rm -f
fi