global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: linux
    static_configs:
      - targets: ['monit-node:9100']
        labels:
          instance: db1

  - job_name: mysql
    static_configs:
      - targets: ['monit-mysql:9104']
        labels:
          instance: db1