[base]
path = {base}

[diffusion_webui]
port = 7860:7860
image = diffusion_webui
volumes = {container}data/diffusion/extensions:/home/user/stable-diffusion-webui/models/extensions,{container}data/diffusion/outputs:/home/user/stable-diffusion-webui/outputs
environment = NVIDIA_DISABLE_REQUIRE=1,NVIDIA_DRIVER_CAPABILITIES=all

[comfyui]
port = 8188:8188,3000:3000
image = comfyui
gpus = all


[am]
image = am
port = 8045:8045
environment = API_KEY=shemic,WEB_PASSWORD=123456,ABV_MAX_BODY_SIZE=104857600
volumes = ~/.antigravity_tools:/root/.antigravity_tools

[jimeng]
image = jimeng
port = 8047:8000
environment = TZ=Asia/Shanghai

[opencode]
image = opencode
port = 4030:4096
environment = HOSTNAME_OVERRIDE=0.0.0.0,PORT=4096,MDNS=false,MDNS_DOMAIN=opencode.local,OPENCODE_SERVER_PASSWORD=shemic168,OPENCODE_CONFIG_DIR=/data/config,OPENCODE_CONFIG=/data/config/opencode.json,CORS=[]
volumes = /data/opencode/data:/data,/data/opencode/workspace:/workspace

[vpn]
image = vpn
port = 5000:5000
volumes1 = /data/proxy-data:/proxy/data

[openclaw]
image = openclaw
port = 18789:18789,1455:1455,1420:1420
volumes1 = /data/openclaw:/root/.openclaw

[copaw]
image = copaw
port = 8088:8088
volumes = /data/copaw/data:/app/working

[newapi]
image = newapi
port = 3030:3000
#environment = TZ=Asia/Shanghai,SQL_DSN="root:123456@tcp(web-mysql:3306)/newapi"
environment = TZ=Asia/Shanghai
volumes = /data/newapi/data:/data

[ironclaw]
image = ironclaw

[deeplx]
image = deeplx
port = 1188:1188
environment = TOKEN=shemic,DL_SESSION=shemic168

[pgsql]
image = postgresql
port = 5432:5432
environment = POSTGRES_USER=app,POSTGRES_PASSWORD=tempapp123456jingmei,POSTGRES_DB=jingmei
volumes = /data/origin/postgres:/var/lib/postgresql/data

[temporal]
port = 7233:7233
environment = DB=ai-pgsql,DB_PORT=5432,POSTGRES_USER=app,POSTGRES_PWD=tempapp123456jingmei,POSTGRES_SEEDS=postgres,POSTGRES_DB=jingmei

[temporalui]
image = temporal_ui
port = 8233:8080
environment = TEMPORAL_ADDRESS=ai-temporal:7233

[adminer]
port = 8081:8080

[obsidian]
port = 3031:3000
volumes = /data/obsidian:/vault
environment = CUSTOM_USER=admin,PASSWORD=123456,PUID=1000,PGID=1000

[code]
port = 8080:8080
volumes = /data/code:/home/coder/project
environment = PASSWORD=123456