#!/usr/bin/env bash
name=$1
domain=$2
port=$3
path=$4
pids=`ps aux|grep "SCREEN -dmS $name"|grep -v entrypoint|grep -v grep|grep -v process|awk '{print $2}'`
if [ "$pids" ]; then
    kill -9 $pids
    screen -wipe
fi

screen -dmS $name
cmd=$"ngrok -subdomain=$domain -config=${path}ngrok.cfg $port"
screen -x -S $name -p 0 -X stuff "$cmd"
screen -x -S $name -p 0 -X stuff $'\n'

/usr/bin/expect <<EOF
send "\01"
send "d"
expect eof
EOF