#!/bin/sh
set name [lrange $argv 0 0]
set port [lrange $argv 1 1]

screen -dmS $name
cmd=$"ngrok -subdomain='$name' -config='ngrok.cfg' $port"
screen -x -S $name -p 0 -X stuff "$cmd"
screen -x -S $name -p 0 -X stuff $'\n'

/usr/bin/expect <<EOF #嵌套expect
send "\01" #模拟输入 ctrl-a
send "d" #模拟输入d  ctrl-a+d是挂起screen
expect eof
EOF