#!/usr/bin/env sh
set -e
apt install golang
git clone https://github.com/inconshreveable/ngrok.git --depth=1 ngrok
cp -R ngrokroot.crt ngrok/assets/client/tls/ngrokroot.crt
cd ngrok
GOOS=linux GOARCH=arm make release-client
cp bin/ngrok /usr/bin/ngrok
cd ..
apt install screen
#screen -S ngrok_pan
#ngrok -subdomain="pan" -config="ngrok.cfg" 8030
#ngrok -subdomain="www" -config="ngrok.cfg" 80
#ctrl+A+D